### ISSUE TITLE
Version 0.2.2+ kills href attribute for link

### ISSUE THREAD

**Issue by heavior** [dlanger/inlinestyler#24]
Hello! 

I use inlinestyler for preprocessing mustache-templates for emails.
Initial template has this link: `<a href="{{config.url}}">Home</a>`

And inline_css method encodes href: `<a href="%7B%7Bconfig.url%7D%7D">Home</a>`
After that mustache can't handle this template.

Version 0.2.1 doesn't have this issue. 0.2.2 and 0.2.3 - have

**Comment by dlanger** [comment]
Notwithstanding how it used to work, I think what it does now is the right behaviour? 

There's no way for the package to know if the `{{` in `<a href="{{config.url}}">` are elements in the URL which should be escaped, or if they're template variables.

Could you change the order of your email-building pipeline to do all your substitution first, and then run `inlinestyler` on the result of that? That order would also mean that any URLs you've accidentally used containing escapable characters get properly encoded.

**Comment by heavior** [comment]
Why does it have to do something with hrefs at all? This is pure css inliner, why touch hrefs?

**Comment by dlanger** [comment]
If I had to guess, it was [this change](https://github.com/dlanger/inlinestyler/compare/0.2.1...0.2.2?diff=split&name=0.2.2#diff-9226f4568f5908525c9d30613a7f828dR62) (coming in [here](https://github.com/dlanger/inlinestyler/pull/19)) which introduced it. 

As for the "why", it comes from how the thing works. `inlinestyler` takes the whole HTML document and loads it into an `ElementTree` object. It then performs all the inlining operations on that `etree`, and then writes that structure back out as HTML.

These two conversions aren't noticeable in the case where the input is valid HTML - since HTML on the way in yields the same HTML on the way out. In cases like this, thought, you can see where `ElementTree` is trying to do the right thing by giving us back proper escaped HTML. XML (which was the old output format) doesn't require symbols like this to be escaped, so it didn't change them.

**Comment by heavior** [comment]
Ok, I understand the reason, but I surely didn't expect this behavior. And changing workflow doesn't seem like a good idea (processing css for every email sounds bad). I had to downgrade to 0.2.1

**Comment by dlanger** [comment]
Yeah, you've hit an edge-case - sorry about that.
